filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  
setup.kibana.host: "http://kibana:5601"

processors:
  # - add_cloud_metadata: ~
  # - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elastic:9200"]

filebeat.inputs:
- type: filestream
  id: filebeat-id
  enabled: true
  paths:
    - /var/log/auth.log